### ISSUE TITLE
Ctrl+Meta+arrow Maybe Not work

### ISSUE THREAD

**Issue by HuJJ-NB** [Hegemonia123/FlexGrid#1]
Maybe I get wrong understand of this, I watch your code, but I'm not good at both English and JavaScript, is it mean that I could use the `Ctrl+Meta+Arrow` to change size of windows?
Could you put a example GIF or video, or just tell me what will happen when change the layout, I thought the windows will change size at the same time but nothing happened.
Thanks a lot.

**Comment by Hegemonia123** [comment]
You can use `Ctrl+Meta+Left or right arrow` to switch between layouts / grids. I added a screen recording demonstrating the usage to the README. You may have some conflicting actions assigned to  `Ctrl+Meta+Arrow` -hotkeys. Try setting them manually in KDE settings. 
![Screenshot_20220506_174800](https://user-images.githubusercontent.com/102908263/167157300-7dadc529-ee76-4f55-bc59-f6f3f962fc2a.png)

**Comment by HuJJ-NB** [comment]
Sorry, I guess it's my problem.
First, I change the gap of the default layout, but nothing change, so I guess your script haven't work totally, then I found that I install the `Latte Dock` it has same `Meta+arrow`-hotkeys to move windows, and I try to uninstall your script, I can still use the hotkeys so maybe your script haven't work totally, because I have already install `Latte Dock`.

**Comment by Hegemonia123** [comment]
You can set for example `Ctrl+Meta+Alt+Arrow` combination to layout switching action. It seems though, that you must run `kwin --replace` after the change. I guess this is not a problem in the script itself, because there is no magic in the script regarding registering hotkeys. 
The same applies to changing the gap, you must restart kwin afterwards for the changes to take effect.

**Comment by HuJJ-NB** [comment]
Yes, not the script's fault, I have `twin_x11 in --replace &` at Manjaro(I think it also work).
I guess the `Latte Dock` app I already installed, bind the hotkeys first by a way have priority, I cloud bind the other hotkeys to make it work.
Thanks.
